### PR TITLE
feat: update upstream to 1.5.1

### PR DESCRIPTION
**Pull request by muhlba91**
BREAKING CHANGE: major upstream update to v1

### CODE REVIEW

**Comment by ringods** [comment]
@muhlba91 what is breaking on this? If the internal Pulumi resource types differ, you can automatically remap these using aliases.

Here is an example how we did this to migrate from `aws:s3/bucket:Bucket` to `aws:s3/bucket:BucketV2`:

https://github.com/pulumi/pulumi-aws/blob/eae27fd472dbdf1f0a705e668bf9e6a187d7570f/provider/resources.go#L3305-L3309

**Comment by muhlba91** [comment]
@ringods the buildkite team moved an attribute from the pipeline resource to its own resource (https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/guides/upgrade-v1#removed-features).
if you used this attribute beforehand, you must follow the migration path outlined in their doc.
i wanted to mark with a major version increase/breaking change that 1/ one needs to take care of backwards incompatible changes, and 2/ the buildkite team now considers the terraform provider as stable.

**Comment by muhlba91** [comment]
@ringods unfortunately, this didn't get much attention from my side for a while...
i updated the dependencies now but do believe that the drift in the Buildkite API and Terraform provider is too large at this stage to correct it without a major backward compatibility breaking release.
afaik, there also had been a case where one had to migrate through incremental Terraform provider version updates to not create backward incompatible issues.
can we get this through and create a new major release?

**Comment by runlevel5** [comment]
@muhlba91 wondering if you have a chance to review this PR? Many thanks

**Comment by muhlba91** [comment]
@runlevel5 the problem is that since i'm the author, i cannot give myself a review as per repository requirements.
that means we are waiting for someone from the pulumiverse team to review - @ringods did that so far for this repository, though...

**Comment by runlevel5** [comment]
@muhlba91 while you are at it, could you please bump to 1.5.1? Many thanks

**Comment by runlevel5** [comment]
> @runlevel5 the problem is that since i'm the author, i cannot give myself a review as per repository requirements. that means we are waiting for someone from the pulumiverse team to review - @ringods did that so far for this repository, though...

I am not from the core team but I know enough Go if you don't mind external reviewers.

**Comment by runlevel5** [comment]
Besides, could you please help a look at the linter warning:

```
warning: error: Failure in parsing resource name: buildkite_pipeline, subsection: ## Schema
warning: failed to convert HCL for #/resources/buildkite:Pipeline/pipeline:Pipeline to typescript: #-resources-buildkite:Pipeline-pipeline:Pipeline.pp:5,9-23: unknown property 'build_branches' among [buildPullRequestLabelsChanged buildPullRequests publishCommitStatus pullRequestBranchFilterConfiguration skipBuildsForExistingCommits triggerMode buildBranches prefixPullRequestForkBranchNames filterCondition filterEnabled publishBlockedAsPending pullRequestBranchFilterEnabled buildTags buildPullRequestReadyForReview cancelDeletedBranchBuilds publishCommitStatusPerStep separatePullRequestStatuses skipPullRequestBuildsForExistingCommits buildPullRequestForks]; , and 11 other diagnostic(s)
warning: failed to convert HCL for #/resources/buildkite:Pipeline/pipeline:Pipeline to python: #-resources-buildkite:Pipeline-pipeline:Pipeline.pp:5,9-23: unknown property 'build_branches' among [buildPullRequestLabelsChanged buildPullRequests buildTags skipPullRequestBuildsForExistingCommits buildBranches filterEnabled prefixPullRequestForkBranchNames buildPullRequestReadyForReview publishBlockedAsPending publishCommitStatus publishCommitStatusPerStep pullRequestBranchFilterConfiguration separatePullRequestStatuses skipBuildsForExistingCommits triggerMode filterCondition cancelDeletedBranchBuilds pullRequestBranchFilterEnabled buildPullRequestForks]; , and 11 other diagnostic(s)
warning: failed to convert HCL for #/resources/buildkite:Pipeline/pipeline:Pipeline to csharp: #-resources-buildkite:Pipeline-pipeline:Pipeline.pp:5,9-23: unknown property 'build_branches' among [buildTags cancelDeletedBranchBuilds prefixPullRequestForkBranchNames triggerMode separatePullRequestStatuses skipPullRequestBuildsForExistingCommits buildBranches filterCondition publishCommitStatusPerStep pullRequestBranchFilterEnabled buildPullRequestForks buildPullRequestLabelsChanged buildPullRequestReadyForReview buildPullRequests filterEnabled publishBlockedAsPending publishCommitStatus pullRequestBranchFilterConfiguration skipBuildsForExistingCommits]; , and 11 other diagnostic(s)
warning: failed to convert HCL for #/resources/buildkite:Pipeline/pipeline:Pipeline to go: #-resources-buildkite:Pipeline-pipeline:Pipeline.pp:5,9-23: unknown property 'build_branches' among [buildPullRequests publishBlockedAsPending publishCommitStatus pullRequestBranchFilterConfiguration separatePullRequestStatuses skipBuildsForExistingCommits prefixPullRequestForkBranchNames pullRequestBranchFilterEnabled buildPullRequestForks buildPullRequestReadyForReview buildTags cancelDeletedBranchBuilds filterEnabled triggerMode buildBranches buildPullRequestLabelsChanged filterCondition publishCommitStatusPerStep skipPullRequestBuildsForExistingCommits]; , and 11 other diagnostic(s)
```

**Comment by muhlba91** [comment]
sure, i'll bump it on friday - currently, i'm travelling and will be back tomorrow late evening.

regarding review. the problem is that this org has branch protections and without a review of someone in the org, i can't press the merge button. 😕
i'll try to ping some people again after i updated the used TF provider version to hopefully get some attention on this one.

anyhow, if you can review the PR, i'm pretty sure this would make it easier and faster to get it through once someone from the org reviews it. 👍🏻

as for those warnings, they usually occur because of some examples or documentation provided in the terraform docs. that will affect the automatically generated docs of the pulumi provider/sdks.
i'll double check the warnings on friday as well but in most cases, where i saw it, this is just an upstream TF provider docs issue.

**Review by ringods — APPROVED** [review]
@muhlba91 I approved. Sorry for the delay.

Regarding reviewers: the intent of Pulumiverse is that there is shared maintenance of providers, so I would applaud @runlevel5 to be a co-maintainer. If you add a similar file for @runlevel5 like the one below in a PR to the `infra` repository, you have your co-maintainer.

With the proper `CODEOWNERS` file in your repo afterwards, you can work with the both of you and I'm out of the loop.

**Comment by muhlba91** [comment]
@runlevel5 i updated to `v1.5.1`. could you please provide your review and then we get this released? (i wasn't able to find you in the reviewer list - @ringods is there anything else to do than adding him to the infra repo which already happened?)

**Review by runlevel5 — APPROVED** [review]

**Comment by runlevel5** [comment]
@muhlba91 LGTM 👍

**Comment by ringods** [comment]
@runlevel5 can you accept the invitation to join the `pulumiverse` organization. You should have received an email from Github. Check your spam folder. You are currently still listed as an `Outside collaborator`.

**Pull request merged**
